[package]
name = "cypress-css"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cssparser = { version = "0.33.0", features = ["serde"] }
encoding_rs = "0.8.33"
